<?php
$countries = [
    "AF" => "Afghanistan",
    "AX" => "Åland Islands",
    "AL" => "Albania",
    "DZ" => "Algeria",
    "AS" => "American Samoa",
    "AD" => "Andorra",
    "AO" => "Angola",
    "AI" => "Anguilla",
    "AQ" => "Antarctica",
    "AG" => "Antigua and Barbuda",
    "AR" => "Argentina",
    "AM" => "Armenia",
    "AW" => "Aruba",
    "AC" => "Ascension Island",
    "AU" => "Australia",
    "AT" => "Austria",
    "AZ" => "Azerbaijan",
    "BS" => "Bahamas",
    "BH" => "Bahrain",
    "BD" => "Bangladesh",
    "BB" => "Barbados",
    "BY" => "Belarus",
    "BE" => "Belgium",
    "BZ" => "Belize",
    "BJ" => "Benin",
    "BM" => "Bermuda",
    "BT" => "Bhutan",
    "BO" => "Bolivia",
    "BA" => "Bosnia & Herzegovina",
    "BW" => "Botswana",
    "BV" => "Bouvet Island",
    "BR" => "Brazil",
    "IO" => "British Indian Ocean Territory",
    "VG" => "British Virgin Islands",
    "BN" => "Brunei",
    "BG" => "Bulgaria",
    "BF" => "Burkina Faso",
    "BI" => "Burundi",
    "KH" => "Cambodia",
    "CM" => "Cameroon",
    "CA" => "Canada",
    "IC" => "Canary Islands",
    "CV" => "Cape Verde",
    "BQ" => "Caribbean Netherlands",
    "KY" => "Cayman Islands",
    "CF" => "Central African Republic",
    "EA" => "Ceuta & Melilla",
    "TD" => "Chad",
    "CL" => "Chile",
    "CN" => "China",
    "CX" => "Christmas Island",
    "CP" => "Clipperton Island",
    "CC" => "Cocos (Keeling) Islands",
    "CO" => "Colombia",
    "KM" => "Comoros",
    "CG" => "Congo - Brazzaville",
    "CD" => "Congo - Kinshasa",
    "CK" => "Cook Islands",
    "CR" => "Costa Rica",
    "CI" => "Côte d’Ivoire",
    "HR" => "Croatia",
    "CU" => "Cuba",
    "CW" => "Curaçao",
    "CY" => "Cyprus",
    "CZ" => "Czech Republic",
    "DK" => "Denmark",
    "DG" => "Diego Garcia",
    "DJ" => "Djibouti",
    "DM" => "Dominica",
    "DO" => "Dominican Republic",
    "EC" => "Ecuador",
    "EG" => "Egypt",
    "SV" => "El Salvador",
    "GQ" => "Equatorial Guinea",
    "ER" => "Eritrea",
    "EE" => "Estonia",
    "SZ" => "Eswatini",
    "ET" => "Ethiopia",
    "FK" => "Falkland Islands",
    "FO" => "Faroe Islands",
    "FJ" => "Fiji",
    "FI" => "Finland",
    "FR" => "France",
    "GF" => "French Guiana",
    "PF" => "French Polynesia",
    "TF" => "French Southern Territories",
    "GA" => "Gabon",
    "GM" => "Gambia",
    "GE" => "Georgia",
    "DE" => "Germany",
    "GH" => "Ghana",
    "GI" => "Gibraltar",
    "GR" => "Greece",
    "GL" => "Greenland",
    "GD" => "Grenada",
    "GP" => "Guadeloupe",
    "GU" => "Guam",
    "GT" => "Guatemala",
    "GG" => "Guernsey",
    "GN" => "Guinea",
    "GW" => "Guinea-Bissau",
    "GY" => "Guyana",
    "HT" => "Haiti",
    "HM" => "Heard & McDonald Islands",
    "HN" => "Honduras",
    "HK" => "Hong Kong SAR",
    "HU" => "Hungary",
    "IS" => "Iceland",
    "IN" => "India",
    "ID" => "Indonesia",
    "IR" => "Iran",
    "IQ" => "Iraq",
    "IE" => "Ireland",
    "IM" => "Isle of Man",
    "IL" => "Israel",
    "IT" => "Italy",
    "JM" => "Jamaica",
    "JP" => "Japan",
    "JE" => "Jersey",
    "JO" => "Jordan",
    "KZ" => "Kazakhstan",
    "KE" => "Kenya",
    "KI" => "Kiribati",
    "XK" => "Kosovo",
    "KW" => "Kuwait",
    "KG" => "Kyrgyzstan",
    "LA" => "Laos",
    "LV" => "Latvia",
    "LB" => "Lebanon",
    "LS" => "Lesotho",
    "LR" => "Liberia",
    "LY" => "Libya",
    "LI" => "Liechtenstein",
    "LT" => "Lithuania",
    "LU" => "Luxembourg",
    "MO" => "Macau SAR",
    "MG" => "Madagascar",
    "MW" => "Malawi",
    "MY" => "Malaysia",
    "MV" => "Maldives",
    "ML" => "Mali",
    "MT" => "Malta",
    "MH" => "Marshall Islands",
    "MQ" => "Martinique",
    "MR" => "Mauritania",
    "MU" => "Mauritius",
    "YT" => "Mayotte",
    "EA" => "Melilla",
    "MX" => "Mexico",
    "FM" => "Micronesia",
    "MD" => "Moldova",
    "MC" => "Monaco",
    "MN" => "Mongolia",
    "ME" => "Montenegro",
    "MS" => "Montserrat",
    "MA" => "Morocco",
    "MZ" => "Mozambique",
    "MM" => "Myanmar (Burma)",
    "NA" => "Namibia",
    "NR" => "Nauru",
    "NP" => "Nepal",
    "NL" => "Netherlands",
    "NC" => "New Caledonia",
    "NZ" => "New Zealand",
    "NI" => "Nicaragua",
    "NE" => "Niger",
    "NG" => "Nigeria",
    "NU" => "Niue",
    "NF" => "Norfolk Island",
    "MP" => "Northern Mariana Islands",
    "KP" => "North Korea",
    "MK" => "North Macedonia",
    "NO" => "Norway",
    "OM" => "Oman",
    "PK" => "Pakistan",
    "PW" => "Palau",
    "PS" => "Palestinian Territories",
    "PA" => "Panama",
    "PG" => "Papua New Guinea",
    "PY" => "Paraguay",
    "PE" => "Peru",
    "PH" => "Philippines",
    "PN" => "Pitcairn Islands",
    "PL" => "Poland",
    "PT" => "Portugal",
    "PR" => "Puerto Rico",
    "QA" => "Qatar",
    "RE" => "Réunion",
    "RO" => "Romania",
    "RU" => "Russia",
    "RW" => "Rwanda",
    "BL" => "Saint Barthélemy",
    "LC" => "Saint Lucia",
    "WS" => "Samoa",
    "SM" => "San Marino",
    "ST" => "São Tomé & Príncipe",
    "SA" => "Saudi Arabia",
    "SN" => "Senegal",
    "RS" => "Serbia",
    "SC" => "Seychelles",
    "SL" => "Sierra Leone",
    "SG" => "Singapore",
    "SX" => "Sint Maarten",
    "SK" => "Slovakia",
    "SI" => "Slovenia",
    "SB" => "Solomon Islands",
    "SO" => "Somalia",
    "ZA" => "South Africa",
    "GS" => "South Georgia and the South Sandwich Islands",
    "KR" => "South Korea",
    "SS" => "South Sudan",
    "ES" => "Spain",
    "LK" => "Sri Lanka",
    "SH" => "St. Helena",
    "KN" => "St. Kitts & Nevis",
    "MF" => "St. Martin",
    "PM" => "St. Pierre & Miquelon",
    "VC" => "St. Vincent & Grenadines",
    "SD" => "Sudan",
    "SR" => "Suriname",
    "SJ" => "Svalbard & Jan Mayen",
    "SE" => "Sweden",
    "CH" => "Switzerland",
    "SY" => "Syria",
    "TW" => "Taiwan",
    "TJ" => "Tajikistan",
    "TZ" => "Tanzania",
    "TH" => "Thailand",
    "TL" => "Timor-Leste",
    "TG" => "Togo",
    "TK" => "Tokelau",
    "TO" => "Tonga",
    "TT" => "Trinidad & Tobago",
    "SH" => "Tristan da Cunha",
    "TN" => "Tunisia",
    "TR" => "Turkey",
    "TM" => "Turkmenistan",
    "TC" => "Turks & Caicos Islands",
    "TV" => "Tuvalu",
    "UM" => "U.S. Outlying Islands",
    "VI" => "U.S. Virgin Islands",
    "UG" => "Uganda",
    "UA" => "Ukraine",
    "AE" => "United Arab Emirates",
    "GB" => "United Kingdom",
    "US" => "United States",
    "UY" => "Uruguay",
    "UZ" => "Uzbekistan",
    "VU" => "Vanuatu",
    "VA" => "Vatican City",
    "VE" => "Venezuela",
    "VN" => "Vietnam",
    "WF" => "Wallis & Futuna",
    "EH" => "Western Sahara",
    "YE" => "Yemen",
    "ZM" => "Zambia",
    "ZW" => "Zimbabwe",
];

$industries = [
    "Accounting Firm",
    "Brokerage Firm (Securities and Investments)",
    "Casino/Gaming",
    "Consulting Firm",
    "Credit Union",
    "Cryptoasset Service Provider",
    "Financial Institution (Banking)",
    "Financial Institution (Non Banking)",
    "FinTech",
    "Government (Enforcement)",
    "Government (Regulatory)",
    "Import/Export",
    "Insurance Firm",
    "Law Firm",
    "Luxury Retail",
    "Money Services Business (MSB)",
    "Payment Service Provider",
    "Real Estate",
    "Technology (Software and Services)",
    "Trust",
    "Other"
];

$phone_codes = [
    "US" => ["name" => "United States", "code" => "+1"],
    "AF" => ["name" => "Afghanistan", "code" => "+93"],
    "AL" => ["name" => "Albania", "code" => "+355"],
    "DZ" => ["name" => "Algeria", "code" => "+213"],
    "AS" => ["name" => "American Samoa", "code" => "+1 684"],
    "AD" => ["name" => "Andorra", "code" => "+376"],
    "AO" => ["name" => "Angola", "code" => "+244"],
    "AI" => ["name" => "Anguilla", "code" => "+1 264"],
    "AQ" => ["name" => "Antarctica", "code" => "+672"],
    "AG" => ["name" => "Antigua & Barbuda", "code" => "+1 268"],
    "AR" => ["name" => "Argentina", "code" => "+54"],
    "AM" => ["name" => "Armenia", "code" => "+374"],
    "AW" => ["name" => "Aruba", "code" => "+297"],
    "AC" => ["name" => "Ascension Island", "code" => "+247"],
    "AU" => ["name" => "Australia", "code" => "+61"],
    "AT" => ["name" => "Austria", "code" => "+43"],
    "AZ" => ["name" => "Azerbaijan", "code" => "+994"],
    "BS" => ["name" => "Bahamas", "code" => "+1 242"],
    "BH" => ["name" => "Bahrain", "code" => "+973"],
    "BD" => ["name" => "Bangladesh", "code" => "+880"],
    "BB" => ["name" => "Barbados", "code" => "+1 246"],
    "BY" => ["name" => "Belarus", "code" => "+375"],
    "BE" => ["name" => "Belgium", "code" => "+32"],
    "BZ" => ["name" => "Belize", "code" => "+501"],
    "BJ" => ["name" => "Benin", "code" => "+229"],
    "BM" => ["name" => "Bermuda", "code" => "+1 441"],
    "BT" => ["name" => "Bhutan", "code" => "+975"],
    "BO" => ["name" => "Bolivia", "code" => "+591"],
    "BA" => ["name" => "Bosnia & Herzegovina", "code" => "+387"],
    "BW" => ["name" => "Botswana", "code" => "+267"],
    "BV" => ["name" => "Bouvet Island", "code" => "+47"],
    "BR" => ["name" => "Brazil", "code" => "+55"],
    "IO" => ["name" => "British Indian Ocean Territory", "code" => "+246"],
    "VG" => ["name" => "British Virgin Islands", "code" => "+1 284"],
    "BN" => ["name" => "Brunei", "code" => "+673"],
    "BG" => ["name" => "Bulgaria", "code" => "+359"],
    "BF" => ["name" => "Burkina Faso", "code" => "+226"],
    "BI" => ["name" => "Burundi", "code" => "+257"],
    "KH" => ["name" => "Cambodia", "code" => "+855"],
    "CM" => ["name" => "Cameroon", "code" => "+237"],
    "CA" => ["name" => "Canada", "code" => "+1"],
    "IC" => ["name" => "Canary Islands", "code" => "+34"],
    "CV" => ["name" => "Cape Verde", "code" => "+238"],
    "BQ" => ["name" => "Caribbean Netherlands", "code" => "+599"],
    "KY" => ["name" => "Cayman Islands", "code" => "+1 345"],
    "CF" => ["name" => "Central African Republic", "code" => "+236"],
    "EA" => ["name" => "Ceuta & Melilla", "code" => "+34"],
    "TD" => ["name" => "Chad", "code" => "+235"],
    "CL" => ["name" => "Chile", "code" => "+56"],
    "CN" => ["name" => "China", "code" => "+86"],
    "CX" => ["name" => "Christmas Island", "code" => "+61"],
    "CP" => ["name" => "Clipperton Island", "code" => "+33"],
    "CC" => ["name" => "Cocos (Keeling) Islands", "code" => "+61"],
    "CO" => ["name" => "Colombia", "code" => "+57"],
    "KM" => ["name" => "Comoros", "code" => "+269"],
    "CG" => ["name" => "Congo - Brazzaville", "code" => "+242"],
    "CD" => ["name" => "Congo - Kinshasa", "code" => "+243"],
    "CK" => ["name" => "Cook Islands", "code" => "+682"],
    "CR" => ["name" => "Costa Rica", "code" => "+506"],
    "HR" => ["name" => "Croatia", "code" => "+385"],
    "CU" => ["name" => "Cuba", "code" => "+53"],
    "CW" => ["name" => "Curaçao", "code" => "+599"],
    "CY" => ["name" => "Cyprus", "code" => "+357"],
    "CZ" => ["name" => "Czechia", "code" => "+420"],
    "CI" => ["name" => "Côte d’Ivoire", "code" => "+225"],
    "DK" => ["name" => "Denmark", "code" => "+45"],
    "DG" => ["name" => "Diego Garcia", "code" => "+246"],
    "DJ" => ["name" => "Djibouti", "code" => "+253"],
    "DO" => ["name" => "Dominican Republic", "code" => "+1 809"],
    "DM" => ["name" => "Dominica", "code" => "+1 767"],
    "EC" => ["name" => "Ecuador", "code" => "+593"],
    "EG" => ["name" => "Egypt", "code" => "+20"],
    "SV" => ["name" => "El Salvador", "code" => "+503"],
    "GQ" => ["name" => "Equatorial Guinea", "code" => "+240"],
    "ER" => ["name" => "Eritrea", "code" => "+291"],
    "EE" => ["name" => "Estonia", "code" => "+372"],
    "SZ" => ["name" => "Eswatini", "code" => "+268"],
    "ET" => ["name" => "Ethiopia", "code" => "+251"],
    "FK" => ["name" => "Falkland Islands", "code" => "+500"],
    "FO" => ["name" => "Faroe Islands", "code" => "+298"],
    "FJ" => ["name" => "Fiji", "code" => "+679"],
    "FI" => ["name" => "Finland", "code" => "+358"],
    "FR" => ["name" => "France", "code" => "+33"],
    "GF" => ["name" => "French Guiana", "code" => "+594"],
    "PF" => ["name" => "French Polynesia", "code" => "+689"],
    "TF" => ["name" => "French Southern Territories", "code" => "+262"],
    "GA" => ["name" => "Gabon", "code" => "+241"],
    "GM" => ["name" => "Gambia", "code" => "+220"],
    "GE" => ["name" => "Georgia", "code" => "+995"],
    "DE" => ["name" => "Germany", "code" => "+49"],
    "GH" => ["name" => "Ghana", "code" => "+233"],
    "GI" => ["name" => "Gibraltar", "code" => "+350"],
    "GR" => ["name" => "Greece", "code" => "+30"],
    "GL" => ["name" => "Greenland", "code" => "+299"],
    "GD" => ["name" => "Grenada", "code" => "+1 473"],
    "GP" => ["name" => "Guadeloupe", "code" => "+590"],
    "GU" => ["name" => "Guam", "code" => "+1 671"],
    "GT" => ["name" => "Guatemala", "code" => "+502"],
    "GG" => ["name" => "Guernsey", "code" => "+44"],
    "GN" => ["name" => "Guinea", "code" => "+224"],
    "GW" => ["name" => "Guinea-Bissau", "code" => "+245"],
    "GY" => ["name" => "Guyana", "code" => "+592"],
    "HT" => ["name" => "Haiti", "code" => "+509"],
    "HM" => ["name" => "Heard & McDonald Islands", "code" => "+672"],
    "HN" => ["name" => "Honduras", "code" => "+504"],
    "HK" => ["name" => "Hong Kong", "code" => "+852"],
    "HU" => ["name" => "Hungary", "code" => "+36"],
    "IS" => ["name" => "Iceland", "code" => "+354"],
    "IN" => ["name" => "India", "code" => "+91"],
    "ID" => ["name" => "Indonesia", "code" => "+62"],
    "IR" => ["name" => "Iran", "code" => "+98"],
    "IQ" => ["name" => "Iraq", "code" => "+964"],
    "IE" => ["name" => "Ireland", "code" => "+353"],
    "IM" => ["name" => "Isle of Man", "code" => "+44"],
    "IL" => ["name" => "Israel", "code" => "+972"],
    "IT" => ["name" => "Italy", "code" => "+39"],
    "JM" => ["name" => "Jamaica", "code" => "+1 876"],
    "JP" => ["name" => "Japan", "code" => "+81"],
    "JE" => ["name" => "Jersey", "code" => "+44"],
    "JO" => ["name" => "Jordan", "code" => "+962"],
    "KZ" => ["name" => "Kazakhstan", "code" => "+7"],
    "KE" => ["name" => "Kenya", "code" => "+254"],
    "KI" => ["name" => "Kiribati", "code" => "+686"],
    "XK" => ["name" => "Kosovo", "code" => "+383"],
    "KW" => ["name" => "Kuwait", "code" => "+965"],
    "KG" => ["name" => "Kyrgyzstan", "code" => "+996"],
    "LA" => ["name" => "Laos", "code" => "+856"],
    "LV" => ["name" => "Latvia", "code" => "+371"],
    "LB" => ["name" => "Lebanon", "code" => "+961"],
    "LS" => ["name" => "Lesotho", "code" => "+266"],
    "LR" => ["name" => "Liberia", "code" => "+231"],
    "LY" => ["name" => "Libya", "code" => "+218"],
    "LI" => ["name" => "Liechtenstein", "code" => "+423"],
    "LT" => ["name" => "Lithuania", "code" => "+370"],
    "LU" => ["name" => "Luxembourg", "code" => "+352"],
    "MO" => ["name" => "Macau", "code" => "+853"],
    "MG" => ["name" => "Madagascar", "code" => "+261"],
    "MW" => ["name" => "Malawi", "code" => "+265"],
    "MY" => ["name" => "Malaysia", "code" => "+60"],
    "MV" => ["name" => "Maldives", "code" => "+960"],
    "ML" => ["name" => "Mali", "code" => "+223"],
    "MT" => ["name" => "Malta", "code" => "+356"],
    "MH" => ["name" => "Marshall Islands", "code" => "+692"],
    "MQ" => ["name" => "Martinique", "code" => "+596"],
    "MR" => ["name" => "Mauritania", "code" => "+222"],
    "MU" => ["name" => "Mauritius", "code" => "+230"],
    "YT" => ["name" => "Mayotte", "code" => "+262"],
    "MX" => ["name" => "Mexico", "code" => "+52"],
    "FM" => ["name" => "Micronesia", "code" => "+691"],
    "MD" => ["name" => "Moldova", "code" => "+373"],
    "MC" => ["name" => "Monaco", "code" => "+377"],
    "MN" => ["name" => "Mongolia", "code" => "+976"],
    "ME" => ["name" => "Montenegro", "code" => "+382"],
    "MS" => ["name" => "Montserrat", "code" => "+1 664"],
    "MA" => ["name" => "Morocco", "code" => "+212"],
    "MZ" => ["name" => "Mozambique", "code" => "+258"],
    "MM" => ["name" => "Myanmar (Burma)", "code" => "+95"],
    "NA" => ["name" => "Namibia", "code" => "+264"],
    "NR" => ["name" => "Nauru", "code" => "+674"],
    "NP" => ["name" => "Nepal", "code" => "+977"],
    "NL" => ["name" => "Netherlands", "code" => "+31"],
    "NC" => ["name" => "New Caledonia", "code" => "+687"],
    "NZ" => ["name" => "New Zealand", "code" => "+64"],
    "NI" => ["name" => "Nicaragua", "code" => "+505"],
    "NE" => ["name" => "Niger", "code" => "+227"],
    "NG" => ["name" => "Nigeria", "code" => "+234"],
    "NU" => ["name" => "Niue", "code" => "+683"],
    "NF" => ["name" => "Norfolk Island", "code" => "+672"],
    "MP" => ["name" => "Northern Mariana Islands", "code" => "+1 670"],
    "KP" => ["name" => "North Korea", "code" => "+850"],
    "MK" => ["name" => "North Macedonia", "code" => "+389"],
    "NO" => ["name" => "Norway", "code" => "+47"],
    "OM" => ["name" => "Oman", "code" => "+968"],
    "PK" => ["name" => "Pakistan", "code" => "+92"],
    "PW" => ["name" => "Palau", "code" => "+680"],
    "PS" => ["name" => "Palestinian Territories", "code" => "+970"],
    "PA" => ["name" => "Panama", "code" => "+507"],
    "PG" => ["name" => "Papua New Guinea", "code" => "+675"],
    "PY" => ["name" => "Paraguay", "code" => "+595"],
    "PE" => ["name" => "Peru", "code" => "+51"],
    "PH" => ["name" => "Philippines", "code" => "+63"],
    "PN" => ["name" => "Pitcairn Islands", "code" => "+64"],
    "PL" => ["name" => "Poland", "code" => "+48"],
    "PT" => ["name" => "Portugal", "code" => "+351"],
    "PR" => ["name" => "Puerto Rico", "code" => "+1"],
    "QA" => ["name" => "Qatar", "code" => "+974"],
    "RO" => ["name" => "Romania", "code" => "+40"],
    "RU" => ["name" => "Russia", "code" => "+7"],
    "RW" => ["name" => "Rwanda", "code" => "+250"],
    "RE" => ["name" => "Réunion", "code" => "+262"],
    "WS" => ["name" => "Samoa", "code" => "+685"],
    "SM" => ["name" => "San Marino", "code" => "+378"],
    "SA" => ["name" => "Saudi Arabia", "code" => "+966"],
    "SN" => ["name" => "Senegal", "code" => "+221"],
    "RS" => ["name" => "Serbia", "code" => "+381"],
    "SC" => ["name" => "Seychelles", "code" => "+248"],
    "SL" => ["name" => "Sierra Leone", "code" => "+232"],
    "SG" => ["name" => "Singapore", "code" => "+65"],
    "SX" => ["name" => "Sint Maarten", "code" => "+1 721"],
    "SK" => ["name" => "Slovakia", "code" => "+421"],
    "SI" => ["name" => "Slovenia", "code" => "+386"],
    "SB" => ["name" => "Solomon Islands", "code" => "+677"],
    "SO" => ["name" => "Somalia", "code" => "+252"],
    "ZA" => ["name" => "South Africa", "code" => "+27"],
    "GS" => ["name" => "South Georgia & Sandwich islands", "code" => "+500"],
    "KR" => ["name" => "South Korea", "code" => "+82"],
    "SS" => ["name" => "South Sudan", "code" => "+211"],
    "ES" => ["name" => "Spain", "code" => "+34"],
    "LK" => ["name" => "Sri Lanka", "code" => "+94"],
    "BL" => ["name" => "St. Barthélemy", "code" => "+590"],
    "SH" => ["name" => "St. Helena", "code" => "+290"],
    "KN" => ["name" => "St. Kitts & Nevis", "code" => "+1 869"],
    "LC" => ["name" => "St. Lucia", "code" => "+1 758"],
    "MF" => ["name" => "St. Martin", "code" => "+590"],
    "PM" => ["name" => "St. Pierre & Miquelon", "code" => "+508"],
    "VC" => ["name" => "St. Vincent & Grenadines", "code" => "+1 784"],
    "SD" => ["name" => "Sudan", "code" => "+249"],
    "SR" => ["name" => "Suriname", "code" => "+597"],
    "SJ" => ["name" => "Svalbard & Jan Mayen", "code" => "+47"],
    "SE" => ["name" => "Sweden", "code" => "+46"],
    "CH" => ["name" => "Switzerland", "code" => "+41"],
    "SY" => ["name" => "Syria", "code" => "+963"],
    "ST" => ["name" => "São Tomé & Príncipe", "code" => "+239"],
    "TW" => ["name" => "Taiwan", "code" => "+886"],
    "TJ" => ["name" => "Tajikistan", "code" => "+992"],
    "TZ" => ["name" => "Tanzania", "code" => "+255"],
    "TH" => ["name" => "Thailand", "code" => "+66"],
    "TL" => ["name" => "Timor-Leste", "code" => "+670"],
    "TG" => ["name" => "Togo", "code" => "+228"],
    "TK" => ["name" => "Tokelau", "code" => "+690"],
    "TO" => ["name" => "Tonga", "code" => "+676"],
    "TT" => ["name" => "Trinidad & Tobago", "code" => "+1 868"],
    "TA" => ["name" => "Tristan da Cunha", "code" => "+290"],
    "TN" => ["name" => "Tunisia", "code" => "+216"],
    "TR" => ["name" => "Turkey", "code" => "+90"],
    "TM" => ["name" => "Turkmenistan", "code" => "+993"],
    "TC" => ["name" => "Turks & Caicos Islands", "code" => "+1 649"],
    "TV" => ["name" => "Tuvalu", "code" => "+688"],
    "UG" => ["name" => "Uganda", "code" => "+256"],
    "UA" => ["name" => "Ukraine", "code" => "+380"],
    "AE" => ["name" => "United Arab Emirates", "code" => "+971"],
    "GB" => ["name" => "United Kingdom", "code" => "+44"],
    "UY" => ["name" => "Uruguay", "code" => "+598"],
    "UZ" => ["name" => "Uzbekistan", "code" => "+998"],
    "UM" => ["name" => "U.S. Outlying Islands", "code" => "+246"],
    "VI" => ["name" => "U.S. Virgin Islands", "code" => "+1"],
    "VU" => ["name" => "Vanuatu", "code" => "+678"],
    "VA" => ["name" => "Vatican City", "code" => "+379"],
    "VE" => ["name" => "Venezuela", "code" => "+58"],
    "VN" => ["name" => "Vietnam", "code" => "+84"],
    "WF" => ["name" => "Wallis & Futuna", "code" => "+681"],
    "EH" => ["name" => "Western Sahara", "code" => "+212"],
    "YE" => ["name" => "Yemen", "code" => "+967"],
    "ZM" => ["name" => "Zambia", "code" => "+260"],
    "ZW" => ["name" => "Zimbabwe", "code" => "+263"],
    "AX" => ["name" => "Åland Islands", "code" => "+358"],
];
